<a href="https://colab.research.google.com/github/shreyasstha/data/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
mat = np.array([[1,2], [3,4]])
print(arr)
print(mat)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
print(arr.shape)      # (4,) → 1D with 4 elements
print(mat.shape)      # (2, 2)
print(arr.dtype)

(4,)
(2, 2)
int64


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a=np.array([10,20,30,40,50,60,70])
print(a[0])
print(a[-2])

10
30


In [ ]:
print(a[2]+a[3])

70


In [ ]:
#slicing
print(a[1:3])
print(a[1:])
print(a[:1])
print(a[::2])
print(a[1:6:2])


[20 30]
[20 30 40]
[10]
[10 30]
[20 40]


In [ ]:
#for 2D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0,1])
print(arr[1,3])

2
9


In [ ]:
print(arr[1, 1:3])
print(arr[0, 2:])
print(arr[0, 1:4:2])

[7 8]
[3 4 5]
[2 4]


In [ ]:
#shape and reshape
arr=np.array([0,1,2,3,4,5])
newarr=arr.reshape(2,3)
print(newarr)

[[0 1 2]
 [3 4 5]]


In [ ]:
a=np.arange(6)
a=a.reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.shape)
newarr=arr.reshape(-1)
print(newarr)

(2, 5)
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#sort
arr=np.array([3,6,1,8,0,2,5,7,4])
print(np.sort(arr))

[0 1 2 3 4 5 6 7 8]


In [ ]:
#adding=join
a=np.array([0,1,2])
b=np.array([3,4,5])
arr=np.concatenate((a,b))
print(arr)

[0 1 2 3 4 5]


In [ ]:
arr1=np.hstack((a,b))  #horizontal/row
arr2=np.vstack((a,b))  #vertical
arr3=np.dstack((a,b))  #along height
print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[[0 3]
  [1 4]
  [2 5]]]


data type


In [ ]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [ ]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']
